// Color tokens — mirrors app/theme.py exactly
export const colors = {
  bg:       '#04070F',
  surface:  '#080E1A',
  surface2: '#0C1526',
  surface3: '#111D31',
  border:   '#162035',
  border2:  '#1E2E48',
  text:     '#EEF2FA',
  text2:    '#A8B5CC',
  muted:    '#526280',
  pulse:    '#00E5A0',
  pulseDim: '#00A370',
  glow:     'rgba(0,229,160,0.12)',
  gold:     '#F5C518',
  green:    '#00D26A',
  blue:     '#3B82F6',
  yellow:   '#FBBF24',
  amber:    '#F97316',
  red:      '#EF4444',
}

export const tierColors: Record<string, string> = {
  Green:  colors.green,
  Yellow: colors.yellow,
  Amber:  colors.amber,
  Red:    colors.red,
}

export const bandColors: Record<string, string> = {
  Excellent: colors.green,
  Good:      colors.blue,
  Fair:      colors.yellow,
  Watch:     colors.amber,
  Critical:  colors.red,
}

export const FEATURE_LABELS: Record<string, string> = {
  EXT_MEAN:                     'Avg External Bureau Score',
  EXT_SOURCE_2:                 'External Bureau Score 2',
  EXT_SOURCE_3:                 'External Bureau Score 3',
  EXT_SOURCE_1:                 'External Bureau Score 1',
  CREDIT_INCOME_RATIO:          'Credit-to-Income Ratio',
  ANNUITY_INCOME_RATIO:         'Annuity-to-Income Ratio',
  PAYMENT_CREDIT_RATIO:         'Payment-to-Credit Ratio',
  INCOME_PER_PERSON:            'Income per Family Member',
  DAYS_BIRTH:                   'Age at Application',
  DAYS_EMPLOYED:                'Employment Duration',
  EMPLOYED_AGE_RATIO:           'Employment-to-Age Ratio',
  AMT_INCOME_TOTAL:             'Annual Income',
  AMT_CREDIT:                   'Loan Credit Amount',
  AMT_ANNUITY:                  'Annual Annuity Due',
  EMPLOYED_ANOM:                'Employment Anomaly Flag',
  BUREAU_LOAN_COUNT:            'Total Bureau Credits',
  BUREAU_ACTIVE_COUNT:          'Active Bureau Credits',
  BUREAU_DEBT_CREDIT_RATIO:     'Bureau Debt/Credit Ratio',
  BUREAU_DPD_RATIO:             'Bureau DPD Frequency',
  BUREAU_CREDIT_DAY_OVERDUE_MEAN:'Avg Bureau Overdue Days',
  PREV_COUNT:                   'Prior Application Count',
  PREV_REFUSED_RATIO:           'Prior Refusal Rate',
  PREV_APPROVED_RATIO:          'Prior Approval Rate',
  INST_LATE_RATIO:              'Late Payment Rate',
  INST_LATE_DAYS_MEAN:          'Avg Late Payment Days',
  INST_UNDERPAY_RATIO:          'Underpayment Frequency',
  INST_PAYMENT_INSTALMENT_RATIO:'Repayment Rate',
  POS_DPD_MEAN:                 'POS Cash Avg DPD',
  CC_UTILIZATION_MEAN:          'Avg Card Utilization',
  CC_UTILIZATION_MAX:           'Peak Card Utilization',
  CC_MIN_PAYMENT_MISS_RATIO:    'Missed Min Payment Rate',
  CC_DPD_MEAN:                  'Card Avg DPD',
}
